
import { Language, LocalizationStrings } from './types';

export const LOCALES: Record<Language, LocalizationStrings> = {
  [Language.EN]: {
    title: 'Nur-kitoblar',
    settings: 'Settings',
    library: 'Catalog',
    reader: 'Read',
    upload: 'Upload Book',
    aiVoiceChat: 'AI Voice Chat',
    bookSummary: 'Book Summary',
    audioBook: 'Audio Library',
    aiAudio: 'AI Narration',
    languageSelect: 'Interface Language',
    startLive: 'Start Conversation',
    stopLive: 'End Session',
    ocrProcessing: 'Scanning document...',
    noFileSelected: 'No book selected',
    extractText: 'Start Reading',
    voiceLanguage: 'Voice Language',
    autoDetect: 'Auto-detect',
    summarize: 'Quick Summary',
    summarizingStatus: 'Generating insights...',
    summarizingDrafting: 'Summarizing content...',
    summaryTitle: 'Deep Analysis',
    close: 'Close',
    aiCompanion: 'Digital Assistant',
    askAnything: 'Ask about any book...',
    analyzeImage: 'Analyze Visuals',
    visionProcessing: 'Interpreting visuals...',
    chatPlaceholder: 'How can I assist your reading today?',
    dropFile: 'Drag & Drop PDF or Photo',
    processingPdf: 'AI is analyzing the entire volume...',
    downloadCover: 'Download Cover',
    downloadPdf: 'Download PDF',
    getPdf: 'Get PDF'
  },
  [Language.UZ]: {
    title: 'Nur-kitoblar',
    settings: 'Sozlamalar',
    library: 'Katalog',
    reader: 'O‘qish',
    upload: 'Kitob yuklash',
    aiVoiceChat: 'AI Ovozli Chat',
    bookSummary: 'Kitob Xulosasi',
    audioBook: 'Audio Kutubxona',
    aiAudio: 'AI Audiolashtirish',
    languageSelect: 'Ilova tili',
    startLive: 'Suhbatni boshlash',
    stopLive: 'Suhbatni yakunlash',
    ocrProcessing: 'Hujjat skan qilinmoqda...',
    noFileSelected: 'Kitob tanlanmagan',
    extractText: 'Mutolaani boshlash',
    voiceLanguage: 'Ovoz tili',
    autoDetect: 'Avtomatik aniqlash',
    summarize: 'Tezkor xulosa',
    summarizingStatus: 'Tahlil qilinmoqda...',
    summarizingDrafting: 'Xulosa tayyorlanmoqda...',
    summaryTitle: 'Chuqur tahlil',
    close: 'Yopish',
    aiCompanion: 'Raqamli yordamchi',
    askAnything: 'Kitob haqida savol bering...',
    analyzeImage: 'Tasvir tahlili',
    visionProcessing: 'Tasvirlar o‘rganilmoqda...',
    chatPlaceholder: 'Bugun sizga qanday yordam bera olaman?',
    dropFile: 'PDF yoki rasm faylni shu yerga tashlang',
    processingPdf: 'AI butun kitobni tahlil qilmoqda...',
    downloadCover: 'Muqovani yuklash',
    downloadPdf: 'PDFni yuklash',
    getPdf: 'PDFni olish'
  },
  [Language.RU]: {
    title: 'Нур-китоблар',
    settings: 'Настройки',
    library: 'Каталог',
    reader: 'Чтение',
    upload: 'Загрузить книгу',
    aiVoiceChat: 'AI Голосовой Чат',
    bookSummary: 'Краткое содержание',
    audioBook: 'Аудиотека',
    aiAudio: 'AI Озвучка',
    languageSelect: 'Язык интерфейса',
    startLive: 'Начать беседу',
    stopLive: 'Завершить сессию',
    ocrProcessing: 'Сканирую документ...',
    noFileSelected: 'Книга не выбрана',
    extractText: 'Начать чтение',
    voiceLanguage: 'Язык голоса',
    autoDetect: 'Автоопределение',
    summarize: 'Итоги',
    summarizingStatus: 'Генерирую идеи...',
    summarizingDrafting: 'Пишу резюме...',
    summaryTitle: 'Глубоческий анализ',
    close: 'Закрыть',
    aiCompanion: 'Цифровой помощник',
    askAnything: 'Спросите о любой книге...',
    analyzeImage: 'Анализ визуала',
    visionProcessing: 'Изучаю изображения...',
    chatPlaceholder: 'Чем я могу помочь вам сегодня?',
    dropFile: 'Перетащите PDF или фото',
    processingPdf: 'AI анализирует всё издание...',
    downloadCover: 'Скачать обложку',
    downloadPdf: 'Скачать PDF',
    getPdf: 'Получить PDF'
  },
  [Language.TR]: {
    title: 'Nur-kitaplar',
    settings: 'Ayarlar',
    library: 'Katalog',
    reader: 'Oku',
    upload: 'Kitap Yükle',
    aiVoiceChat: 'AI Sesli Sohbet',
    bookSummary: 'Kitap Özeti',
    audioBook: 'Sesli Kütüphane',
    aiAudio: 'AI Seslendirme',
    languageSelect: 'Arayüz Dili',
    startLive: 'Sohbeti Başlat',
    stopLive: 'Oturumu Bitir',
    ocrProcessing: 'Belge taranıyor...',
    noFileSelected: 'Kitap seçilmedi',
    extractText: 'Okumaya Başla',
    voiceLanguage: 'Ses Dili',
    autoDetect: 'Otomatik Algıla',
    summarize: 'Hızlı Özet',
    summarizingStatus: 'İçgörüler oluşturuluyor...',
    summarizingDrafting: 'Özetleniyor...',
    summaryTitle: 'Derin Analiz',
    close: 'Kapat',
    aiCompanion: 'Dijital Asistan',
    askAnything: 'Herhangi bir kitap hakkında sor...',
    analyzeImage: 'Görselleri Analiz Et',
    visionProcessing: 'Görseller yorumlanıyor...',
    chatPlaceholder: 'Bugün size nasıl yardımcı olabilirim?',
    dropFile: 'PDF veya Fotoğraf Sürükle ve Bırak',
    processingPdf: 'AI tüm cildi analiz ediyor...',
    downloadCover: 'Kapağı İndir',
    downloadPdf: 'PDF İndir',
    getPdf: 'PDF Al'
  },
  [Language.AR]: {
    title: 'نور-كتب',
    settings: 'الإعدادات',
    library: 'الكتالوج',
    reader: 'اقرأ',
    upload: 'تحميل كتاب',
    aiVoiceChat: 'دردشة صوتية بالذكاء الاصطناعي',
    bookSummary: 'ملخص الكتاب',
    audioBook: 'المكتبة الصوتية',
    aiAudio: 'توليد صوتي',
    languageSelect: 'لغة الواجهة',
    startLive: 'بدء المحادثة',
    stopLive: 'إنهاء الجلسة',
    ocrProcessing: 'جاري مسح المستند...',
    noFileSelected: 'لم يتم اختيار كتاب',
    extractText: 'ابدأ القراءة',
    voiceLanguage: 'لغة الصوت',
    autoDetect: 'كشف تلقائي',
    summarize: 'ملخص سريع',
    summarizingStatus: 'جاري إنشاء الأفكار...',
    summarizingDrafting: 'جاري التلخيص...',
    summaryTitle: 'تحليل عميق',
    close: 'إغلاق',
    aiCompanion: 'مساعد رقمي',
    askAnything: 'اسأل عن أي كتاب...',
    analyzeImage: 'تحليل البصريات',
    visionProcessing: 'جاري تفسير البصريات...',
    chatPlaceholder: 'كيف يمكنني مساعدتك اليوم؟',
    dropFile: 'اسحب وأفلت ملف PDF أو صورة',
    processingPdf: 'الذكاء الاصطناعي يحلل المجلد بالكامل...',
    downloadCover: 'تحميل الغلاف',
    downloadPdf: 'تحميل PDF',
    getPdf: 'احصل على PDF'
  }
};

export const PREBUILT_VOICES = ['Kore', 'Puck', 'Charon', 'Fenrir', 'Zephyr'];
